from enum import Enum

class ErrorCode(str, Enum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    REGISTRATION_FAILED = "REGISTRATION_FAILED"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"