from handlers.strategies.keyword_count import KeywordExtractor


CASES: list[tuple[str, str | None]] = [
    ('how many notes mention rent?', 'rent'),
    ('how many notes mention budget?', 'budget'),
    ('how many notes talk about debt?', 'debt'),
    ('how many notes discuss anxiety?', 'anxiety'),
    ('how many notes reference meetings?', 'meetings'),
    ('how many notes about photography?', 'photography'),
    ("how many times did I mention 'budget'?", 'budget'),
    ("how many times does 'deadline' appear in my notes?", 'deadline'),
    ("how many notes mention 'budget planning'?", 'budget planning'),
    ("how many notes contain the phrase 'action items'?", 'action items'),
    ("count occurrences of 'follow up' across my notes", 'follow up'),
    ("how many times have I written 'follow up'?", 'follow up'),
    ("how many notes mention 'don't forget'?", "don't forget"),
    ('how many notes mention "budget planning"?', 'budget planning'),
    ('how often did I write about exercise?', 'exercise'),
    ('how frequently did I mention meditation?', 'meditation'),
    ('do I reference deadlines frequently?', 'deadlines'),
    ('count notes that reference Python', 'Python'),
    ('count notes that mention travel', 'travel'),
    ('count occurrences of meeting across my notes', 'meeting'),
    ('count entries referencing deadlines', 'deadlines'),
    ('count budget', 'budget'),
    ('number of notes mentioning meetings', 'meetings'),
    ('number of notes that mention goals', 'goals'),
    ('number of notes mentioning travel', 'travel'),
    ('how many times did I write budget', 'budget'),
    ('how many times did I say RAMA?', 'RAMA'),
    ("how many times have I used the word 'priority'?", 'priority'),
    ("how many times does the word 'focus' show up?", 'focus'),
    ('do I have a lot of notes about work?', 'work'),
    ('do I have many notes on gardening?', 'gardening'),
    ('are there many notes on travel?', 'travel'),
    ('are there several notes about budgeting?', 'budgeting'),
    ('are there a ton of notes about meetings?', 'meetings'),
    ('do I have loads of notes on fitness?', 'fitness'),
    ('do I mention coffee a lot?', 'coffee'),
    ('do I write about fitness much?', 'fitness'),
    ('do I write about sleep often?', 'sleep'),
    ('do I bring up money issues a lot in my journal?', 'money issues'),
    ('is travel a frequent topic in my notes?', 'travel'),
    ('is cooking mentioned a lot?', 'cooking'),
    ('is meditation something I write about often?', 'meditation'),
    ('how many notes mention my manager?', 'manager'),
    ('how many times did I mention the dentist?', 'dentist'),
    ('how many notes reference my manager?', 'manager'),
    ('how many notes include the word productivity?', 'productivity'),
    ("how many notes have the word 'important'?", 'important'),
    ('how many notes about saving money?', 'saving money'),
    ('how many notes talk about saving money?', 'saving money'),
    ('how many notes mention REST API?', 'REST API'),
    ('how many notes mention the project deadline for Q2?', 'project deadline for Q2'),
    ('how many notes mention c++?', 'c++'),
    ('how many notes mention node.js?', 'node.js'),
    ('how many notes mention $500?', '$500'),
    ('how many notes mention to-do?', 'to-do'),
    ('how many notes mention work/life balance?', 'work/life balance'),
    ('do I mention BUDGET a lot?', 'BUDGET'),
    ('how many notes mention Python?', 'Python'),
    ('how many notes mention 🏋️ fitness?', 'fitness'),
    ('how many entries mention rent?', 'rent'),
    ('how many journal entries mention therapy?', 'therapy'),
    ('how many notes are about photography?', 'photography'),
    ('how many notes are related to cooking?', 'cooking'),
    ('budget count', 'budget'),
    ('   how many notes mention  budget  ?', 'budget'),
    ('how many notes mention ...budget?', 'budget'),
    ('how many notes mention ?', None),
    ('how many', None),
    ('count', None),
    ('how many notes mention', None),
    ('how many notes mention morning routine?', 'morning routine'),
    ('how many notes talk about meal prep?', 'meal prep'),
    ('how many notes reference side hustle?', 'side hustle'),
    ('did I mention coffee?', 'coffee'),
    ('is there anything about travel in my notes?', 'travel'),
    ('check if I wrote about budgeting', 'budgeting'),
    ('how many notes mention work from home policy?', 'work from home policy'),
    ('how many notes talk about mental health awareness?', 'mental health awareness'),
    ("how many notes mention manager's feedback?", "manager's feedback"),
    ('how many notes mention meeting?', 'meeting'),
    ('how many notes mention running?', 'running'),
    ('how many notes mention self-care?', 'self-care'),
    ('how many notes mention café?', 'café'),
    ('how many notes have budget in them?', 'budget'),
    ('how many of my notes say something about travel?', 'travel'),
    ('notes mentioning rent, how many?', 'rent'),
    ('budget — how many notes?', 'budget'),
    ('tell me how many notes talk about cooking', 'cooking'),
    ('how many notes mention rent?', 'rent'),
    ('how many notes mention budget?', 'budget'),
    ('how many notes talk about debt?', 'debt'),
    ('how many notes discuss anxiety?', 'anxiety'),
    ('how many notes reference meetings?', 'meetings'),
    ('how many notes about photography?', 'photography'),
    ('how many notes mention sleep?', 'sleep'),
    ('how many notes contain travel?', 'travel'),
    ('how many notes include cooking?', 'cooking'),
    ("how many times did I mention 'budget'?", 'budget'),
    ("how many notes mention 'budget planning'?", 'budget planning'),
    ("how many times does 'deadline' appear in my notes?", 'deadline'),
    ("count occurrences of 'follow up' across my notes", 'follow up'),
    ("how many times have I written 'follow up'?", 'follow up'),
    ("how many notes mention 'don't forget'?", "don't forget"),
    ('how many notes mention "budget planning"?', 'budget planning'),
    ("how many notes contain the phrase 'action items'?", 'action items'),
    ("how many notes have the word 'important'?", 'important'),
    ("how many times have I used the word 'priority'?", 'priority'),
    ("how many notes mention 'self-care routine'?", 'self-care routine'),
    ("how many notes mention 'work-life balance'?", 'work-life balance'),
    ("how many times did I write 'note to self'?", 'note to self'),
    ("how many notes mention 'can't stop'?", "can't stop"),
    ("how many notes mention 'it's complicated'?", "it's complicated"),
    ('how many times did I write budget', 'budget'),
    ('how many times did I say RAMA?', 'RAMA'),
    ('how many times did I mention the dentist?', 'dentist'),
    ('how many times did I bring up anxiety?', 'anxiety'),
    ('how many times did I talk about money?', 'money'),
    ('how many times did I note down meeting action items?', 'meeting action items'),
    ('how many times did I reference the landlord?', 'landlord'),
    ('how many times did I discuss career goals?', 'career goals'),
    ("how many times does the word 'focus' show up?", 'focus'),
    ('how many times does budget appear in my notes?', 'budget'),
    ('how many times does rent come up?', 'rent'),
    ('how many times have I mentioned therapy?', 'therapy'),
    ('how many times have I brought up deadlines?', 'deadlines'),
    ('how often did I write about exercise?', 'exercise'),
    ('how often did I mention meditation?', 'meditation'),
    ('how often do I bring up coffee?', 'coffee'),
    ('how often have I referenced travel plans?', 'travel plans'),
    ('how often do I talk about fitness goals?', 'fitness goals'),
    ('how frequently did I mention meditation?', 'meditation'),
    ('how frequently do I write about my manager?', 'manager'),
    ('how regularly do I mention sleep?', 'sleep'),
    ('count notes that reference Python', 'Python'),
    ('count notes that mention travel', 'travel'),
    ('count notes mentioning deadlines', 'deadlines'),
    ('count notes about gardening', 'gardening'),
    ('count notes containing budget', 'budget'),
    ('count notes discussing health', 'health'),
    ('count notes related to cooking', 'cooking'),
    ('count notes on fitness', 'fitness'),
    ('count entries referencing deadlines', 'deadlines'),
    ('count entries mentioning rent', 'rent'),
    ('count occurrences of meeting across my notes', 'meeting'),
    ('count occurrences of the word sleep', 'sleep'),
    ('count instances of anxiety in my notes', 'anxiety'),
    ('count mentions of coffee throughout my notes', 'coffee'),
    ('count uses of the word deadline', 'deadline'),
    ('count budget', 'budget'),
    ('number of notes mentioning meetings', 'meetings'),
    ('number of notes that mention goals', 'goals'),
    ('number of notes mentioning travel', 'travel'),
    ('number of notes referencing budget', 'budget'),
    ('number of notes discussing anxiety', 'anxiety'),
    ('number of entries containing sleep', 'sleep'),
    ('number of notes about meal prep', 'meal prep'),
    ('number of notes related to side hustle', 'side hustle'),
    ('do I have a lot of notes about work?', 'work'),
    ('do I have many notes on gardening?', 'gardening'),
    ('do I have lots of notes about travel?', 'travel'),
    ('do I have several notes about cooking?', 'cooking'),
    ('do I have a ton of notes about meetings?', 'meetings'),
    ('do I have loads of notes on fitness?', 'fitness'),
    ('do I have plenty of notes about budgeting?', 'budgeting'),
    ('do I have a bunch of notes about anxiety?', 'anxiety'),
    ('do I have quite a few notes on meditation?', 'meditation'),
    ('are there many notes on travel?', 'travel'),
    ('are there several notes about budgeting?', 'budgeting'),
    ('are there a ton of notes about meetings?', 'meetings'),
    ('are there a lot of notes about health?', 'health'),
    ('are there lots of notes on productivity?', 'productivity'),
    ('have I got many notes about cooking?', 'cooking'),
    ('do I mention coffee a lot?', 'coffee'),
    ('do I mention deadlines often?', 'deadlines'),
    ('do I mention sleep that much?', 'sleep'),
    ('do I mention rent all the time?', 'rent'),
    ('do I write about fitness much?', 'fitness'),
    ('do I write about sleep often?', 'sleep'),
    ('do I write about anxiety a lot?', 'anxiety'),
    ('do I talk about money a lot?', 'money'),
    ('do I bring up money issues a lot in my journal?', 'money issues'),
    ('do I bring up cooking frequently?', 'cooking'),
    ('do I discuss work a lot?', 'work'),
    ('do I reference deadlines frequently?', 'deadlines'),
    ('do I reference travel regularly?', 'travel'),
    ('do I touch on meditation often?', 'meditation'),
    ('is travel a frequent topic in my notes?', 'travel'),
    ('is cooking mentioned a lot?', 'cooking'),
    ('is meditation something I write about often?', 'meditation'),
    ('is fitness a common topic?', 'fitness'),
    ('is anxiety a recurring theme?', 'anxiety'),
    ('is budget something I mention a lot?', 'budget'),
    ('is sleep mentioned often?', 'sleep'),
    ('is coffee referenced a lot?', 'coffee'),
    ('is work a frequent topic?', 'work'),
    ('is rent brought up often?', 'rent'),
    ('how many notes mention my manager?', 'manager'),
    ('how many notes reference my therapist?', 'therapist'),
    ('how many notes discuss my commute?', 'commute'),
    ('how many times did I mention the dentist?', 'dentist'),
    ('how many times did I bring up the landlord?', 'landlord'),
    ('how many notes include the word productivity?', 'productivity'),
    ('how many notes reference my morning routine?', 'morning routine'),
    ('how many notes about saving money?', 'saving money'),
    ('how many notes talk about saving money?', 'saving money'),
    ('how many notes mention REST API?', 'REST API'),
    ('how many notes mention work from home policy?', 'work from home policy'),
    ('how many notes talk about mental health awareness?', 'mental health awareness'),
    ('how many notes mention morning routine?', 'morning routine'),
    ('how many notes talk about meal prep?', 'meal prep'),
    ('how many notes reference side hustle?', 'side hustle'),
    ('how many notes discuss project deadline for Q2?', 'project deadline for Q2'),
    ('how many notes mention cold showers?', 'cold showers'),
    ('how many notes reference blood pressure?', 'blood pressure'),
    ('how many notes mention time management?', 'time management'),
    ('how many notes mention c++?', 'c++'),
    ('how many notes mention node.js?', 'node.js'),
    ('how many notes mention $500?', '$500'),
    ('how many notes mention to-do?', 'to-do'),
    ('how many notes mention work/life balance?', 'work/life balance'),
    ('how many notes mention C#?', 'C#'),
    ('how many notes mention .NET?', '.NET'),
    ('how many notes mention @home tasks?', '@home tasks'),
    ('how many notes mention #goals?', '#goals'),
    ('how many notes mention 50%?', '50%'),
    ('do I mention BUDGET a lot?', 'BUDGET'),
    ('how many notes mention Python?', 'Python'),
    ('how many notes mention AWS?', 'AWS'),
    ('how many notes mention SQL?', 'SQL'),
    ('how many notes mention iPhone?', 'iPhone'),
    ('how many notes mention 🏋️ fitness?', 'fitness'),
    ('how many notes mention 🧘 meditation?', 'meditation'),
    ('how many notes mention 💰 budget?', 'budget'),
    ('how many notes mention 🍳 cooking?', 'cooking'),
    ('how many entries mention rent?', 'rent'),
    ('how many journal entries mention therapy?', 'therapy'),
    ('how many journal entries discuss anxiety?', 'anxiety'),
    ('how many entries reference fitness?', 'fitness'),
    ('how many entries talk about money?', 'money'),
    ('how many notes are about photography?', 'photography'),
    ('how many notes are related to cooking?', 'cooking'),
    ('how many notes cover leadership?', 'leadership'),
    ('how many notes address burnout?', 'burnout'),
    ('how many notes touch on mindfulness?', 'mindfulness'),
    ('how many notes have budget in them?', 'budget'),
    ('how many notes have meditation in them?', 'meditation'),
    ('how many of my notes say something about travel?', 'travel'),
    ('how many of my notes mention cooking?', 'cooking'),
    ('how many of my notes talk about fitness?', 'fitness'),
    ('notes mentioning rent, how many?', 'rent'),
    ('notes about cooking, how many?', 'cooking'),
    ('budget — how many notes?', 'budget'),
    ('sleep — how many mentions?', 'sleep'),
    ('tell me how many notes talk about cooking', 'cooking'),
    ('tell me how many notes mention fitness', 'fitness'),
    ('can you tell me how many notes reference budget?', 'budget'),
    ('show me how many notes discuss travel', 'travel'),
    ('count budget', 'budget'),
    ('budget count', 'budget'),
    ('count sleep', 'sleep'),
    ('sleep count', 'sleep'),
    ('count meditation', 'meditation'),
    ('   how many notes mention  budget  ?', 'budget'),
    ('how many notes mention ...budget?', 'budget'),
    ('how many notes mention budget...?', 'budget'),
    ('how many notes mention  travel ??', 'travel'),
    ('   count    notes   mentioning    fitness', 'fitness'),
    ('how many notes mention ?', None),
    ('how many', None),
    ('count', None),
    ('how many notes mention', None),
    ('how often?', None),
    ('count notes that', None),
    ('how many notes?', None),
    ('number of notes', None),
    ('did I mention coffee?', 'coffee'),
    ('is there anything about travel in my notes?', 'travel'),
    ('check if I wrote about budgeting', 'budgeting'),
    ('did I ever write about meditation?', 'meditation'),
    ('have I mentioned anxiety?', 'anxiety'),
    ('did I bring up the landlord?', 'landlord'),
    ('have I ever discussed fitness?', 'fitness'),
    ('did I ever note down meeting notes?', 'meeting notes'),
    ('have I touched on public speaking?', 'public speaking'),
    ("how many notes mention manager's feedback?", "manager's feedback"),
    ("how many notes mention it's important?", "it's important"),
    ("how many notes mention I'm tired?", "I'm tired"),
    ("how many notes mention can't sleep?", "can't sleep"),
    ("how many notes mention shouldn't forget?", "shouldn't forget"),
    ('how many notes mention meeting?', 'meeting'),
    ('how many notes mention running?', 'running'),
    ('how many notes mention self-care?', 'self-care'),
    ('how many notes mention café?', 'café'),
    ('how many notes mention résumé?', 'résumé'),
    ('how many notes mention naïve?', 'naïve'),
    ('how many notes have budget in them?', 'budget'),
    ('how many of my notes say something about travel?', 'travel'),
    ('notes mentioning rent, how many?', 'rent'),
    ('budget — how many notes?', 'budget'),
    ('tell me how many notes talk about cooking', 'cooking'),
    ("I'm curious how many notes mention anxiety", 'anxiety'),
    ('I wonder how often I mention sleep', 'sleep'),
    ('just wondering how many notes reference budget', 'budget'),
    ('any idea how many notes mention travel?', 'travel'),
    ('curious if I mention coffee a lot', 'coffee'),
    ('wondering how frequently I discuss fitness', 'fitness'),
    ('would you say I write about health a lot?', 'health'),
    ('seems like I mention budget often, how many times?', 'budget'),
    ('I feel like I write about sleep a lot, is that true?', 'sleep'),
    ('do my notes mention cooking frequently?', 'cooking'),
    ('does travel come up a lot in my notes?', 'travel'),
    ('does fitness appear often in my journal?', 'fitness'),
    ("does the word 'deadline' show up much?", 'deadline'),
    ("what's my most mentioned topic?", None),
    ('which word do I use the most?', None),
    ('what do I write about the most?', None),
    ("what's the most common word in my notes?", None),
    ('what topic comes up the most?', None),
    ('do I mention budget more than travel?', 'budget'),
    ('how many more notes mention cooking than fitness?', 'cooking'),
    ('is sleep mentioned more often than exercise?', 'sleep'),
]

header = f"{'#':<5}{'Query':<65}{'Expected':<26}{'Extracted':<26}{'Result'}"
sep = "\u2500" * len(header)

passed = 0
failed_list: list[tuple[int, str, str | None, str | None]] = []

print(header)
print(sep)

for idx, (query, expected) in enumerate(CASES, 1):
    result = KeywordExtractor.extract(query)
    ok = result == expected
    if ok:
        passed += 1
    else:
        failed_list.append((idx, query, expected, result))

    r_display = str(result) if result is not None else "None"
    e_display = str(expected) if expected is not None else "None"
    mark = "\u2705" if ok else "\u274c"
    print(f"{idx:<5}{query:<65}{e_display:<26}{r_display:<26}{mark}")

print(sep)
total = len(CASES)
print(f"\nResults: {passed}/{total} passed ({100*passed/total:.1f}%)")

if failed_list:
    print(f"\n{'\u2500'*60}")
    print(f"FAILURES ({len(failed_list)}):")
    print(f"{'\u2500'*60}")
    for num, q, exp, got in failed_list:
        print(f'  #{num}: "{q}"')
        print(f'       Expected:  {exp}')
        print(f'       Got:       {got}')
        print()
