from enum import Enum


class ErrorCode(str, Enum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    REGISTRATION_FAILED = "REGISTRATION_FAILED"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    # Agent/chat path. These mirror app/shared/failures.py so a failure keeps
    # the same code whether it is raised here or streamed up from the
    # orchestrator; app/shared/test_failures_in_sync.py checks they agree.
    AGENT_UNAVAILABLE = "AGENT_UNAVAILABLE"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    RATE_LIMITED = "RATE_LIMITED"
    RETRIEVAL_UNAVAILABLE = "RETRIEVAL_UNAVAILABLE"
    TOOL_UNAVAILABLE = "TOOL_UNAVAILABLE"
    TOOL_FAILED = "TOOL_FAILED"
    ACTION_NOT_SUPPORTED = "ACTION_NOT_SUPPORTED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
