#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LLAMA_CPP_DIR="$ROOT_DIR/llama.cpp"
BUILD_DIR="$ROOT_DIR/build"
MODELS_DIR="$ROOT_DIR/models"
ENV_FILE="$ROOT_DIR/.env.llama"
INCLUDE_DIR="$ROOT_DIR/include"

CHAT_MODEL_NAME="${CHAT_MODEL_NAME:-Meta-Llama-3.1-8B-Instruct-Q5_K_M.gguf}"
SUMMARY_MODEL_NAME="${SUMMARY_MODEL_NAME:-mistral_7b_instruct_v0_2_Q5_K_M.gguf}"
CHAT_MODEL_URL="${CHAT_MODEL_URL:-}"
SUMMARY_MODEL_URL="${SUMMARY_MODEL_URL:-}"

log() {
  printf '[setup-llama] %s\n' "$*"
}

require_command() {
  if command -v "$1" >/dev/null 2>&1; then
    return 0
  fi

  if [[ "$1" == "cmake" ]] && command -v brew >/dev/null 2>&1; then
    log "cmake not found. Installing with Homebrew..."
    brew install cmake
    return 0
  fi

  log "Missing required command: $1"
  exit 1
}

download_if_missing() {
  local url="$1"
  local out="$2"

  if [[ -z "$url" ]]; then
    return 0
  fi

  if [[ -f "$out" ]]; then
    log "Model already exists: $out"
    return 0
  fi

  log "Downloading model to $out"
  if [[ -n "${HF_TOKEN:-}" ]]; then
    curl -L --fail --retry 3 -H "Authorization: Bearer ${HF_TOKEN}" -o "$out" "$url"
  else
    curl -L --fail --retry 3 -o "$out" "$url"
  fi
}

cpu_count() {
  if command -v sysctl >/dev/null 2>&1; then
    sysctl -n hw.ncpu 2>/dev/null || echo 4
  else
    echo 4
  fi
}

ensure_repo() {
  local repo_url="$1"
  local dst="$2"
  local label="$3"
  if [[ -d "$dst/.git" ]]; then
    log "$label already present at $dst"
    return 0
  fi
  log "Cloning $label..."
  git clone --depth 1 "$repo_url" "$dst"
}

log "Checking prerequisites..."
require_command git
require_command curl
require_command cmake
require_command make

mkdir -p "$MODELS_DIR"
mkdir -p "$INCLUDE_DIR"

ensure_repo "https://github.com/ggml-org/llama.cpp.git" "$LLAMA_CPP_DIR" "llama.cpp"
ensure_repo "https://github.com/yhirose/cpp-httplib.git" "$INCLUDE_DIR/cpp-httplib" "cpp-httplib"
ensure_repo "https://github.com/nlohmann/json.git" "$INCLUDE_DIR/json" "nlohmann/json"

log "Building inference_api..."
cmake -S "$ROOT_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release -DGGML_METAL=ON
cmake --build "$BUILD_DIR" -j"$(cpu_count)"

download_if_missing "$SUMMARY_MODEL_URL" "$MODELS_DIR/$SUMMARY_MODEL_NAME"
download_if_missing "$CHAT_MODEL_URL" "$MODELS_DIR/$CHAT_MODEL_NAME"

cat > "$ENV_FILE" <<EOF
# Generated by setup_llama.sh
# Load with: source .env.llama

MODEL_PURPOSE_SUMMARIZATION=$MODELS_DIR/$SUMMARY_MODEL_NAME
MODEL_PURPOSE_CHAT=$MODELS_DIR/$CHAT_MODEL_NAME

LLAMA_N_CTX=8192
LLAMA_N_GPU_LAYERS=999
EOF

log "Created $ENV_FILE"
log "If models are missing, place them in $MODELS_DIR with these names:"
log "  - $SUMMARY_MODEL_NAME"
log "  - $CHAT_MODEL_NAME"
log ""
log "Start summarization service (port 8081):"
log "  cd $BUILD_DIR && source ../.env.llama && ./inference_api --port=8081 --mode=summarization"
log "Start chat service (port 8082):"
log "  cd $BUILD_DIR && source ../.env.llama && ./inference_api --port=8082 --mode=summarization"
